# ~/.config/starship.toml

# Disable the package module, hiding it from the prompt completely
[nodejs]
disabled = true
symbol = "ğŸ¤– "

[php]
disabled = false
symbol = "ğŸ˜ "

[ruby]
disabled = true

[git_branch]
symbol = "ğŸŒ± "

[git_status]
conflicted = " ğŸ³ "
ahead = " ğŸğŸ’¨ "
behind = " ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤· "
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green) '
renamed = " ğŸ‘… "
deleted = " ğŸ—‘ "
